### PR TITLE
modify addon_config to generate linkable xcode project

### PR DESCRIPTION
**Pull request by hiroMTB**
Tested on OSX and found I can not generate proper Xcode project from PG because of dylib management.
I put some comment in a addon_config.make file but might be nice to put in README and also change it to correct English since it's bit long and verbose.

### CODE REVIEW

**Comment by hiroMTB** [comment]
Also might be nice to remove existing Xcode project in /example, /example-bodytrack and /example-multicam.

**Comment by pierrep** [comment]
Yeah I'll have a look at this, I had problems with XCode as well. My working example is here: https://github.com/pierrep/OrbecAstraBodyTracker

**Comment by hiroMTB** [comment]
Cool i will check it out.

**Comment by hiroMTB** [comment]
I noticed Astra SDK for OSX is still version 0.5.0.
Thus we can not use same include files. (Now we update to version 2.0.9).

I recommended to make different branch which support different OS with different version of Astra SDK.

**Comment by pierrep** [comment]
Making a separate branch is a good idea - I just did that and added the Mac headers. I had so much pain getting the dylibs working (I have screenshots in https://github.com/pierrep/ofxOrbbecAstra/tree/master/docs) that I forgot about the headers differing.

Btw I've also updated Linux and tested the Windows version, everything seems good.

**Comment by hiroMTB** [comment]
> I had so much pain getting the dylibs working

True. I assume original concept of dylib is "shared" library, which meant to be installed in system directory like /usr/local/lib etc. This way all apps can find it and link against it from everywhere. So it is tricky if we want to make standalone app which has dylib inside. I found that dylibbundler is useful for this standalone app creation.

In this case with Astra, I think we can ask users to install dylib in somewhere like /usr/local/lib or ~/Documents/Astra and always link against it without copying into .app.

**Pull request closed without merging**
